export const inputStyles = {
  section: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  sectionTitle: {
    fontSize: "20px",
    fontWeight: "600",
    color: "#374151",
    margin: 0,
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  inputGroup: {
    display: "flex",
    flexDirection: "column",
  },
  label: {
    fontSize: "14px",
    fontWeight: "500",
    color: "#374151",
    marginBottom: "4px",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  input: {
    width: "100%",
    padding: "12px",
    border: "2px solid #d1d5db",
    borderRadius: "8px",
    fontSize: "16px",
    transition: "all 0.2s",
    boxSizing: "border-box",
  },
  inputError: {
    borderColor: "#ef4444",
  },
  select: {
    width: "100%",
    padding: "12px",
    border: "2px solid #d1d5db",
    borderRadius: "8px",
    fontSize: "16px",
    backgroundColor: "white",
    transition: "all 0.2s",
    boxSizing: "border-box",
  },
  selectDisabled: {
    backgroundColor: "#f3f4f6",
    cursor: "not-allowed",
  },
  phoneContainer: {
    display: "flex",
    gap: "8px",
  },
  countryCodeSelect: {
    minWidth: "120px",
    padding: "12px",
    border: "2px solid #d1d5db",
    borderRadius: "8px",
    fontSize: "16px",
    backgroundColor: "white",
  },
  passwordContainer: {
    position: "relative",
  },
  passwordToggle: {
    position: "absolute",
    right: "12px",
    top: "50%",
    transform: "translateY(-50%)",
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "#6b7280",
    fontSize: "18px",
  },
  error: {
    color: "#ef4444",
    fontSize: "14px",
    marginTop: "4px",
  },
};
